backends/alpm/pk-alpm-transaction.c

I'm not sure about all the g_return_if_fail().
Most of the changes are inspired from pacman 4.2 's  src/pacman/callback.c

Pacman 4.2 support

---

backends/alpm/pk-alpm-packages.c
backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-transaction.c

With this PR I'm merging code `from pk_backend_install_thread` and `pk_backend_update_packages_thread` into `pk_backend_sync_thread`.
As in alpm logic both operations are the same (sync).

Alpm sync thread

---

src/org.freedesktop.PackageKit.xml
src/pk-engine.c

Add dbus method for returning prepared packages

---

backends/alpm/pk-alpm-sync.c

Installing a package with packagekit resulted in everything being
install with install reason asdep. Set install reason to asexplicit
where needed.
This should fix #62

alpm: set install reason to explicitly installed

---

backends/hif/pk-backend-hif.c

These two fixes should make PackageKit match DNF behaviour when dealing with kernel updates and fix up https://bugzilla.redhat.com/show_bug.cgi?id=1205649 that nearly made it to F22 blocker list.

hif: Improve parallel kernel installation

---

contrib/command-not-found/PackageKit.sh.in

https://bugzilla.redhat.com/show_bug.cgi?id=1164410

CNF: Don't run if bash command completion is being run

---

src/pk-backend-job.c

pk_backend_job_thread_setup may run and try to free the thread object
before g_thread_new has returned. The fix is to not store the thread
object inside the job; just do g_thread_unref (g_thread_new (...));
Thanks to Matthias Clasen for pointing out the potential fix.
https://bugzilla.redhat.com/show_bug.cgi?id=1057781

backend job: Fix a race with thread creation

---

backends/portage/portageBackend.py
lib/python/packagekit/progress.py

A couple of fixes and enhancements to the portage backend and python helper classes.

Portage backend step #2

---

backends/alpm/pk-alpm-config.c
backends/alpm/pk-backend-alpm.h
configure.ac

Allan confirmed that libalpm will be version 10.0.0. We should be safe to merge this.

Pacman 5.0

---

backends/alpm/pk-alpm-packages.c

Don't discard a resolve call just because one package is missing

---

docs/html/pk-matrix.html

The Hif backend is gone, with the Dnf backend superseding it.

docs: Replace instances of "hif" with "dnf"

---

.travis.yml
tests/ci/Dockerfile-debian
tests/ci/Dockerfile-fedora
tests/ci/build_and_test.sh

Compiles the project on debian stretch and fedora
See results: https://travis-ci.org/aleixpol/PackageKit (will have to enable it on hugsie after merging)

First approach to a CI

---

po/cs.po

trivial: Update Czech translation

---

lib/packagekit-glib2/pk-client-sync.c

Noticed a push without a pop and vice versa.

Add missing context pushes and pops

---

backends/alpm/pk-alpm-environment.c
client/pk-console.c
docs/setting-the-proxy.txt
lib/packagekit-glib2/pk-control-sync.c
src/pk-backend-spawn.c
src/pk-backend.c
src/pk-backend.h
src/pk-transaction-db.c

These patches include several fixes for session proxy settings, and some updates to outdated docs.

Make proxy settings work

---

backends/aptcc/apt-utils.cpp

origin may contain any number of nonesense, strip everything but words and
digits out!
specifically comma is breaking offline updates as the list of 'prepared'
packages is joined using comma, so having lingering commas in our package
ids utterly breaks splitting of the list and thus the offline update as a
whole.
seeing as origin is entirely free form it is probably wise to be very
aggressive in what we remove.
I've also added a bunch more details to the formats involved here for
prosperity and future reference.

aptcc: fix offline updates by sanitizing origin more aggressively

---

backends/aptcc/apt-intf.cpp

previously we would try to send RequireRestart in the dtor of AptIntf. this
emission was rejected by pk (supposedly because the transaction is
finished by that time already).
to fix this the RequireRestart was moved to surround the actual
installation/removal of packages making the signal sent before the
transaction is finished but after all packages are finished.
Fixes #234

aptcc: fix RequireRestart emission by moving it out of destructor

---

backends/zypp/pk-backend-zypp.cpp

There is a memory leak related to variable 'items' when remove package
thread function fails. This commit moved the pool 'items' to the stack
inside all functions where 'items' is used with a dynamic allocation.
This approach avoids clean up/free structures inside the code.
Signed-off-by: Julio Faracco <jfaracco@br.ibm.com>

zypp: removing memory leak from zypp backend [v2].

---

backends/dnf/Makefile.am
backends/dnf/dnf-backend-vendor-openmandriva.c
configure.ac

Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>

Add OpenMandriva vendor to dnf backend

---

lib/packagekit-glib2/pk-client-helper.c

These could otherwise trigger on a deleted object.

De-register callbacks on PkClientHelper finalize.

---

lib/packagekit-glib2/pk-client-helper.c

- Fix buffer overflow writing nul character on the end of debconf reads
- Register IO callbacks on the thread main context - not the default context (broken in ac3b14be9e)
- Always accept incoming socket connections to avoid busy loop
- Fix loops from incorrect handling of various input error cases
- Close helper stdin when socket closes - was causing debconf UI to remain open and unresponsive
- Use standard IO priority to avoid busy loops
- Reliably clean up socket file on finalize

Fix issues with debconf helper not working:

---

backends/aptcc/apt-cache-file.cpp
backends/aptcc/apt-cache-file.h
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h

Updated version of #253 that also fixes a corner case.

 aptcc: Only autoremove packages that relate to the current transaction 

---

backends/aptcc/apt-utils.cpp

Signed-off-by: Guillem Jover <guillem@debian.org>

aptcc: Update section mappings

---

backends/dnf/pk-backend-dnf.c
configure.ac
lib/packagekit-glib2/pk-common.c
src/pk-shared.c

@hughsie Can you take a quick look please?

Misc. fixes for the dnf backend

---

docs/html/pk-bugs.html

Correct bug tracker links on website

---

src/pk-backend.c

pk_is_thread_default() check was introduced in commit 44bd3ab6 to
detect possible threading problems.
Some backends need call pk_backend_is_eula_valid() in a thread which is
not the default one to perform EULA related actions. This way
pk_is_thread_default() check fails.
Fix that by removing the pk_is_thread_default() check in
pk_backend_is_eula_valid().
Fixes #300

Remove pk_is_thread_default check in pk_backend_is_eula_valid

---

backends/zypp/pk-backend-zypp.cpp

Some fixes to how upgrades are handled, there really is not much point in removing packages from pool for upgrade action. Also to remain the same as zypper in calculated solution, added check for vendor change configuration.

[zypp] Perform actions disallowed by update in upgrade mode

---

backends/aptcc/Makefile.am
backends/aptcc/acqpkitstatus.cpp
backends/aptcc/acqpkitstatus.h
backends/aptcc/apt-cache-file.h
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-utils.cpp
backends/aptcc/deb-file.cpp
backends/aptcc/pk-backend-aptcc.cpp
backends/aptcc/pkg-list.h
configure.ac

Port to APT 1.9

---

contrib/gstreamer-plugin/pk-gstreamer-install.c

support non-x86 arches in gstreamer helper

---

backends/zypp/pk-backend-zypp.cpp

There are a few fixes for the zypp backend. Let's merge all those PR into this one.

Zypp backend fixes

---

client/pk-console.c

For #347
Work pretty well in most cases, except when termux prompts for authentication which still get the staircase in a high rise from progress bar scanning.

* Shrink the progress bar to fit when run in small spaces

---

backends/alpm/pk-alpm-update.c

[backends/alpm] Emit UpdatesChanged when amount of available updates changes

---

backends/alpm/pk-alpm-transaction.c

Fixes #70.
Prevents percentage from regressing to 0% for package downloads and prevents percentage from being emitted as 173,503% for database downloads.

alpm: improve dlcb handling

---

backends/alpm/pk-alpm-sync.c

This better replicates libalpm's behavior and fixes https://bugs.archlinux.org/task/45709.

alpm: respect ignored packages on update

---

contrib/command-not-found/pk-command-not-found.c

Instead of joining the orignal arguments with spaces and executing
with g_spawn_command_line_sync use g_spawn_sync with a new argv[]
built from exec + arguments so we respect the original command line
arguments

command-not-found: fix handling arguments with spaces (fixes #416)

---

backends/aptcc/acqpkitstatus.cpp
backends/aptcc/apt-cache-file.cpp
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-sourceslist.cpp
backends/aptcc/apt-sourceslist.h
backends/aptcc/apt-utils.cpp
backends/aptcc/pk-backend-aptcc.cpp
backends/dummy/pk-backend-dummy.c
client/pk-console.c
contrib/gtk-module/pk-gtk-module.c
lib/packagekit-glib2/pk-bitfield.c
lib/packagekit-glib2/pk-client-helper.c
lib/packagekit-glib2/pk-progress-bar.c
lib/packagekit-glib2/pk-socket-example.c
lib/packagekit-glib2/pk-task.c
lib/packagekit-glib2/pk-test-daemon.c
meson.build
src/pk-backend-job.h
src/pk-engine.c
src/pk-scheduler.c
src/pk-self-test.c
src/pk-transaction.c

I did a bit of housekeeping.
Pretty much all of these changes are trivial, but it's better to have someone else just have a quick look at this patch, just in case I missed something :-)

Fix all compiler warnings

---

backends/dnf/pk-backend-dnf.c

Currently, even if we have "install_weak_deps=False" in
/etc/dnf/dnf.conf, `pkcon install` still tries to install all
the recommended packages.
For avoiding that, we need to inform libdnf that we will
solve the goal of the transaction ourselves (by means of the
dnf_transaction_set_dont_solve_goal() API) and then explicitly
set the flag for ignoring the weak dependencies.
This fixes issue #486 and also solve
https://bugzilla.redhat.com/show_bug.cgi?id=1955484

dnf-backend: honor install_weak_deps=False if it is there

---

po/pl.po

The text was ungrammatical, "te" is plural and "narzędzie" is singular.

pl: "To narzędzie"

---

data/packagekit.service.in

Line was erroneously placed in [Service] and not in [Unit] as required by the spec.

Move Wants= line for network-online.target

---

docs/html/pk-users.html

[Apper](https://invent.kde.org/system/apper/-/commits/master) is pretty much in maintenance mode, [Discover](https://invent.kde.org/plasma/discover/-/commits/master) is under active development.

Replace apper with Discover

---

backends/alpm/meson.build
backends/alpm/pk-alpm-config.c
backends/alpm/pk-alpm-error.c
backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-transaction.c
backends/alpm/pk-alpm-update.c
backends/alpm/pk-alpm-update.h
backends/alpm/pk-backend-alpm.c

This is the current code we use to build the Arch Linux package `packagekit` `1.2.3-4`.

Pacman 6.0.0

---

backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-update.c

Most of them are details but they work.
It includes a crash fix.

ALPM: Address some issues I experienced

---

backends/alpm/pk-alpm-update.c

Change use of `uptate` to `update` in `pk_alpm_refresh_databases`

Fix misspelling of `update`

---

backends/nix/meson.build
backends/nix/nix-lib-plus.cc
backends/nix/pk-backend-nix.cc

Looks like we need to do this every six weeks, compiles, hope this works.
See also https://github.com/NixOS/nix/commit/a385e51
/cc @matthewbauer @jtojnar

Nix: fix build with Nix 2.9.0

---

policy/org.freedesktop.packagekit.policy.in

Fixes https://github.com/PackageKit/PackageKit/issues/567

trivial: Remove unused PolicyKit action

---

src/org.freedesktop.PackageKit.Transaction.xml

Decorates the new arguments that have a complex type.

Fixes the build of PackageKitQt

---

CONTRIBUTING
HACKING

We've long since accepted contributions via GitHub pull requests, so we should indicate as much. Additionally, provide lightweight guidance about how to structure patches matching what we do today.
Finally, add a symlink to point CONTRIBUTING to HACKING.

HACKING: Refresh to match current practices

---

lib/packagekit-glib2/pk-enum.h

Related: https://github.com/PackageKit/PackageKit/pull/603#discussion_r1193163823
cc @Conan-Kudo

PkGroupEnum: avoid ABI change for the newly added value

---

lib/packagekit-glib2/pk-client.c
src/pk-scheduler.c
src/pk-transaction.c

See the commit messages for details.

pk-transaction: Improvements to Finished signals

---

AUTHORS
backends/freebsd/DedupPackageJobEmitter.hpp
backends/freebsd/Deleters.hpp
backends/freebsd/Jobs.hpp
backends/freebsd/PKJobCanceller.hpp
backends/freebsd/PackageDatabase.hpp
backends/freebsd/PackageView.hpp
backends/freebsd/meson.build
backends/freebsd/pk-backend-freebsd.cpp
backends/freebsd/stolen.c
backends/freebsd/xstring.h

This PR implements PackageKit backend for the FreeBSD `pkg`. It is not completely finished, but we're using it for months together with Plasma Discover for basic package management.

FreeBSD backend

---

docs/offline-updates.txt

Update outdated offline-updates.txt

docs: Update outdated offline-updates.txt

---

lib/packagekit-glib2/pk-client.c

The GSimpleAsyncResult API is deprecated and can be replaced by GTask, also avoid copying the GError when set.

PkClient: Replace the GSimpleAsyncResult with the GTask API

---

lib/packagekit-glib2/pk-offline-private.c

This is only needed to handle backends where we receive multiple `PK_INFO_ENUM_INSTALLING` (apt) / `PK_INFO_ENUM_UPDATING` status for a single package update.
Fixes https://github.com/PackageKit/PackageKit/issues/645

offline-updates: Add only one entry per package to 'offline-update-competed' file

---

lib/packagekit-glib2/pk-control.c
lib/packagekit-glib2/pk-package-sack.c
lib/packagekit-glib2/pk-task.c

No API/ABI change here, use the modern GLib API for async operations.

Replace all the GSimpleAsyncResult from the library with the GTask API 

---

.cirrus.yml

While there, switch CI image to FreeBSD 13.3

Enable building FreeBSD backend on FreeBSD CI

---

client/pk-console.c

pkcon: Use appropriate finish call for each async call

---

lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-control.c
lib/packagekit-glib2/pk-package-sack.c
lib/packagekit-glib2/pk-task.c

We now use `finish-func` gir annotation to fix the following warnings.
```
../lib/packagekit-glib2/pk-package-sack.h:147: Warning: PackageKitGlib: Couldn't find 'resolve_finish' for the corresponding async function: 'resolve_async'
../lib/packagekit-glib2/pk-package-sack.h:155: Warning: PackageKitGlib: Couldn't find 'get_details_finish' for the corresponding async function: 'get_details_async'
../lib/packagekit-glib2/pk-package-sack.h:163: Warning: PackageKitGlib: Couldn't find 'get_update_detail_finish' for the corresponding async function: 'get_update_detail_async'
../lib/packagekit-glib2/pk-client.h:119: Warning: PackageKitGlib: Couldn't find 'resolve_finish' for the corresponding async function: 'resolve_async'
../lib/packagekit-glib2/pk-client.h:128: Warning: PackageKitGlib: Couldn't …
```

Fix 'g-ir-scanner' matching async / finish warning

---

src/pk-engine.c

This enables the inhibiting feature with ConsoleKit too.
ConsoleKit and logind and have identical interfaces in this regard.

Decouple pk-backend from HAVE_SYSTEMD_SD_LOGIN_H

---

backends/alpm/meson.build
backends/alpm/pk-alpm-config.c
backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-transaction.c
backends/alpm/pk-alpm-update.c

Handle with care, especially the last one.

alpm 15.0.0 compatibility and build fixes

---

src/pk-engine.c

PackageKit does not offer an API to change the post-update action between reboot and shutdown, so when KDE Plasma wanted to expose this feature it got implemented by calling Trigger(action) at logout time \[1] \[2].
That seems to work fine for offline-updates because by default Trigger() can be called without polkit asking for authentication.
However, for system-upgrades instead TriggerUpgrade() requires authentication. That causes a polkit dialog to appear behind the logout screen, causing bug \[3].
If a system-upgrade was already triggered, merely changing the post-update action should not be a sensitive operation so we can allow that to proceed without prompting polkit.
\[1]: https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/4649
\[2]: …

Allow changing offline update action without polkit authentication

---

lib/packagekit-glib2/pk-client.c

Rename refcount to remaining_files_to_copy to avoid mixing reference counts with time to live.
Change the documentation around pk_client_state_finish as it is really not derefencing PkClientState.
Take a reference on PkClientState while copying a file to make sure that it always live long enough.

PkClient: Use g_atomic_int for the copy count

---

client/pk-console.c

```
$ pkcon
Usage:
pkcon [OPTION…] PackageKit Console Program
PackageKit Console Interface
Subcommands:
backend-details
get-roles
get-groups
get-filters
get-transactions
get-time
search [name|details|group|file] [data]
install [packages]
install-local [files]
download [directory] [packages]
install-sig [type] [key_id] [package_id]
remove [package]
update [package]
refresh [force]
resolve [package]
get-updates
depends-on [package]
required-by [package]
get-details [package]
get-files [package]
get-update-detail [package]
get-packages
repo-list
repo-enable [repo_id]
repo-disable [repo_id]
repo-remove [repo_id] [autoremove]
what-provides [search]
repair
offline-get-prepared
offline-trigger
offline-cancel
offline-status
quit
```
```
$ pkcon 
Usage:
pkcon [OPTION…] PackageKit Console Program …
```

pkcon: Sort commands in 'pkcon' help output

---

lib/packagekit-glib2/pk-task.c

No functional change but use the latest GObject coding standards.

pk-task: Modernize the codebase

---

backends/zypp/pk-backend-zypp.cpp

Fix zypp compiler errors and warnings

---

lib/packagekit-glib2/pk-package.c

Use G_DEFINE_TYPE_WITH_PRIVATE, notify with pspec when possible, use the latest syntax (from more than a decade ago) on the return documentation.

PkPackage: Modernize the codebase

---

lib/packagekit-glib2/pk-progress.c

Refer: https://github.com/PackageKit/PackageKit/pull/834#issuecomment-2800078345

PkProgress: Add missing properties for 'set_property()'

---

.github/workflows/build-test.yml
tests/ci/Dockerfile-fedora

Add alpm and zypp backends to Fedora CI

---

.github/workflows/build-test.yml
tests/ci/Dockerfile-debian
tests/ci/check-abi.sh

Add automated ABI check with abigail.

ci: Check ABI with last know good one

---

backends/zypp/pk-backend-zypp.cpp

Please refer commit log.
Tested on openSUSE Leap 16.0 on top of `PackageKit-1.3.1` (custom installation)
- `gnome-software` is installed.
- `gnome-builder` is not installed.
```
sid@opensuse-leap-16:~/rpmbuild/SPECS> rpm -qi  "/var/cache/zypp/packages/openSUSE:repo-oss/x86_64/gnome-builder-48.2-bp160.1.2.x86_64.rpm" | grep ^Size
Size        : 26738841
sid@opensuse-leap-16:~/rpmbuild/SPECS> rpm -qi gnome-software | grep ^Size
Size        : 3658188
sid@opensuse-leap-16:~/rpmbuild/SPECS> ls -l "/var/cache/zypp/packages/openSUSE:repo-oss/x86_64/gnome-builder-48.2-bp160.1.2.x86_64.rpm"
-rw-r--r--. 1 root root 12393500 Aug 15 20:13 /var/cache/zypp/packages/openSUSE:repo-oss/x86_64/gnome-builder-48.2-bp160.1.2.x86_64.rpm
sid@opensuse-leap-16:~/rpmbuild/SPECS> 
```
``` …
```

zypp: Use pk_backend_job_details_full() to report download size 
