backends/hif/pk-backend-hif.c

I think this concept should be based on user's trust of a GPG key or
something more flexible.  Moving it to PackageKit is cleaner as it's
PK that has the concept of "supported", not libhif.

backends/hif: Move hif_source_is_supported() here

---

backends/alpm/pk-alpm-sync.c

Fix #36 
Before this fix I was asked to proceed or not with installation. With this code, I'm no longer asked for confirmation. I think it was a question from libalpm and now with the right workflow there is no more question.

alpm: honor simulation when installing packages

---

backends/alpm/pk-alpm-remove.c
backends/alpm/pk-alpm-transaction.c

This PR is to fix #39.
I fixed a bad event usage in case of package removal but I still have some strange behavior.
If I remove the ncdu package with `./pkcon remove ncdu` I get the following output :
```
Resolving                     [=========================]         
Testing changes               [=========================]         
Finished                      [=========================]         
Removing                      [=========================]         
Waiting for authentication    [=========================]         
Finished                      [=========================]         
Fatal error: ncdu: could not find or read package
```
On the daemon side I have :
```
./run-pk.sh alpm
packagekitd: no process found
22:58:04	PackageKit          Verbose debugging enabled (on …
```

alpm: fix remove package

---

backends/alpm/pk-alpm-transaction.c
backends/alpm/pk-backend-alpm.c
backends/alpm/pk-backend-alpm.h

This PR is about fixing #15 . Here I'm monitoring /var/lib/pacman/local for changes.
As I asked in #15, is this what I must do here or I should also watch repos synced dbs or only the synced db or something else ?
I also have an other question about `pk_backend_transaction_inhibit_start` are those required and in which case I should call it ? I looked at hif calls but I don't have enought knowledge of the hif backend to understand the behavior.
About the code, I think I'm doing things right with threads and memory. But any reviews are welcome.
cc @hughsie @aleixpol @kalev

alpm: track local db changes and invalidate cache

---

src/pk-backend.c
src/pk-backend.h

This let backend know if the current transaction is inhibited.

Add pk_backend_is_transaction_inhibited

---

backends/alpm/pk-alpm-config.c
backends/alpm/pk-alpm-databases.c
backends/alpm/pk-alpm-databases.h
backends/alpm/pk-alpm-packages.c
backends/alpm/pk-alpm-transaction.c
backends/alpm/pk-backend-alpm.c
backends/alpm/pk-backend-alpm.h

When localdb is modified outside packagekit, we need to do a reload of localdb contents to drop internal caches. To avoid any race condition, caches are dropped on next transaction.

Track pacman changes

---

lib/packagekit-glib2/pk-offline.c
lib/packagekit-glib2/pk-test-private.c

This will allow the user to specify systemd.unit=system-update.target
on the kernel boot line to initiate pending updates.

Make "reboot" the default action for no action file

---

contrib/command-not-found/PackageKit.sh.in
contrib/command-not-found/pk-command-not-found.c

(At least on Fedora,) `/etc/profile.d/PackageKit.sh` is sourced by zsh already, but the hook function is [named differently in zsh](http://zsh.sourceforge.net/Doc/Release/Command-Execution.html). The first patch defines that function when running under zsh, which makes everything *work*.
The second is cosmetic: the name `bash` is currently hardcoded, which makes the mimicked "command not found" messages stick out. However, as described by [the zsh docs](http://zsh.sourceforge.net/Doc/Release/Command-Execution.html), zsh prints out its own message after the hook returns non-zero. So we get something like this:
```
[wjt@gelf]~/src/PackageKit% does-not-exist
zsh: does-not-exist: command not found...
zsh: command not found: does-not-exist
```
where the first message comes from …

zsh support for command-not-found

---

client/pk-offline-update.c

This is a comma splice (http://en.wikipedia.org/wiki/Comma_splice), and while it's probably horribly pedantic to even mention it, it stares me in the face, taunting, whenever I update my system — so I eventually had to say something.  :)

Correct punctuation displayed to users while applying offline updates

---

backends/entropy/entropyBackend.py
backends/portage/portageBackend.py
configure.ac

I tried to fix some issue with the following backend:
- Fixed parameters number passed to the remove function;
- Added search by name if nothing was found in search_details, this because with gnome-packagekit the search function was completely unusable without this fix;
- Applied various patches found [here](http://data.gpo.zugaina.org/gnome/app-admin/packagekit-base/files/) from Gilles Dartiguelongue <eva@gentoo.org> to make things works again;
- Fixed parameters number passed to the remove function;

Fixing issue from entropy and portage backends

---

lib/packagekit-glib2/pk-task-sync.c
lib/packagekit-glib2/pk-task.c

Fix 'packages' arguments in pk_task_resolve_sync / pk_task_resolve_async
which weren't marked as string arrays.

libpackagekit-glib: Fix introspection annotations for pk_task_resolve_*

---

client/pk-offline-update.c

To cooperate with other things using system-update.target, the
recommended behavior is to check to see if we prepared the update,
and if not, exit quietly so as to let the other updater run.
(http://lists.freedesktop.org/archives/systemd-devel/2015-July/033623.html)
This patch makes pk-offline-update check for the action file and the
prepared update transaction; if those don't exist, exit successfully.
Resolves: rhbz#1252500

pk-offline-update: exit quietly if we didn't prepare the update

---

lib/packagekit-glib2/PackageKitGlib-1.0.metadata

Those are useful functions, and it is possible to use them in Vala

Allow the use of variadic functions in vala.

---

lib/packagekit-glib2/PackageKitGlib-1.0.metadata

The default sentinel is NULL which is wrong for these two functions.

vala: Add sentinel flag to variadic functions.

---

data/packagekit-offline-update.service.in

Looks like anything changed in systemd v228 that makes it skip to start
dbus. We need it for offline update, so add a Requires= to unit file.
This should fix Arch Linux downstream bug:
https://bugs.archlinux.org/task/47234

require dbus.socket for offline update

---

backends/zypp/pk-backend-zypp.cpp

b47f98 changed a bunch of gchar* to const gchar* to address some memory leaks.
uri should not have been touched - and it is being g_free()'d as needed.

zypp: fix build

---

backends/aptcc/apt-intf.cpp

The apt history.log file contains log information when apt runs. By setting the "PACKAGEKIT_CALLER_UID" environment apt will log the calling user in the new "requested-by" tag. 
The "CommandLine::AsString" config option is also recorded in the log. The information stored is mostly useful so that an admin can see that this operation was performed using packagekit.

Improve apts "history.log" logfile when using packagekit

---

backends/zypp/pk-backend-zypp.cpp

Testing for a volatile URL scheme (cd/dvd) can be done directly.
There's no point in accessing the media for this.  Creating the handler is quite expensive and at the end it does nothing else but testing the URL scheme.
```
bool
MediaManager::isChangeable(MediaAccessId accessId)
{
return url(accessId).getScheme() == "cd" || url(accessId).getScheme() == "dvd";
}
```
```
bool Url::schemeIsVolatile( const std::string & scheme_r )
{
static const char * val[] = { "cd", "dvd" };
return isInList( arrayBegin(val), arrayEnd(val), scheme_r );
}
```

zypp: Avoid needless media access when testing for cd/dvd URL scheme

---

backends/zypp/pk-backend-zypp.cpp

Allow installing 32-bit x86 packages on 64-bit x86.

zypp: Update arch compatiblity check for x86

---

backends/zypp/pk-backend-zypp.cpp

A number of calls were implicitly handling data as strings, which can be manipulated in unforeseen ways. It also broke the build when `-Werror=format-security` was included in the compiler flags (as it is by default on Fedora).
This is now changed to explicitly declare the input is a string.
This pull request fixes #108.

zypp: Enforce formatting input as string

---

lib/packagekit-glib2/pk-task.c

We had the pk_task_get/set_only_trusted API, but it didn't do much for most transaction types as it was still hardcoded to PK_TRANSACTION_FLAG_ENUM_ONLY_TRUSTED; this fixes it to check the property instead of hardcoding it.

task: Honour the only_trusted property when setting up transactions

---

backends/alpm/pk-alpm-config.c

I have not been able to figure out what I am missing in my attempt to add full support of the `Usage` config key (which can be found here: https://github.com/hughsie/PackageKit/compare/master...lots0logs:tmp122) ..so for now let's just avoid the daemon crashing by ignoring the key. This in effect means that PK will search, install, and update from all repos listed in `pacman.conf` no matter what. This shouldn't be a big deal because honestly any users who are adding `Usage` values to their config should know enough about it to realize that PK is ignoring it.
Fixes #122

Simply ignore the "Usage" key instead of crashing

---

backends/hif/Makefile.am
backends/hif/hif-backend-vendor-fedora.c
backends/hif/hif-backend-vendor-mageia.c
backends/hif/hif-backend-vendor.h
backends/hif/pk-backend-hif.c
configure.ac

With Mageia moving forward to adopt the PackageKit-Hif backend, it is now necessary to support switching out Fedora-specific and Mageia-specific configurations at build time.
For now, this only contains <strike>swapping out repository directory locations and validating the appropriate prefixes for verifying</strike> supported sources.<strike> Fedora isn't yet using `/etc/distro.repos.d`, and other distributions in the future may use other locations</strike>. Obviously sources would differ among distributions.
In the future, support may be added for dealing with groups, which different distributions use different conventions.
I'm somewhat uncertain about the `configure.ac` modifications, because I'm not very good with autotools, but it seemed to select as I wanted to.
This pull request …

hif: Add support for build-time vendor configurations

---

backends/aptcc/pk-backend-aptcc.cpp

at least with shared-mime-info 1.5 the actual mimetype is
application/vnd.debian.binary-package
```
$ mimetype ~/Downloads/steam_latest.deb
/home/me/Downloads/steam_latest.deb: application/vnd.debian.binary-package
```

fix aptcc mimetype list

---

backends/aptcc/pk-backend-aptcc.cpp

Updates were broken in the previous local-file resolution change by eliminating it implicitly being handled in the resolution's else case. They are now once again handled as regular installs.
Additionally force expressiveness in the code by making the else case an error condition (couldn't do anything with the role) and explicitly handling local file in an else-if case.

fix updates and change code to aid in not breaking this again

---

backends/zypp/pk-backend-zypp.cpp

Fix for [boo#981011 - PackageKit dumps core](https://bugzilla.opensuse.org/981011).
If a package ID passed to `backend_get_update_detail` does not resolve to a valid solvable, subsequent code must not try to retrieve any data as all pointer derived from this solvable will be
NULL. In the current code this leads to a SEGV.

zypp: Return error if invalid package IDs are detected

---

contrib/command-not-found/PackageKit.sh.in

I think by now pretty much all distros moved to /run
alternatively we could do something like:
> [[ ! -S /run/dbus/system_bus_socket -a ! -S /var/run/dbus/system_bus_socket ]] &&
Thus checking for both locations and accepting either of the two

command-not-found: Look for dbus socket in /run instead of /var/run

---

contrib/cron/packagekit-background

This format is well understood and it documents the config a bit more verbose
than the original format

Change the configuration of the cron script to a sysconfig-like config

---

lib/packagekit-glib2/pk-task.h
src/pk-backend-job.c

1. Remove declaration for non-existent function `pk_task_{get,set}_interactive()`
It's a property of pk_client only.  There are no properties which exist on both pk_client and pk_task.
2. Fix "cache-age changed to -1" debug message.  (When cache-age is G_MAXUINT)

Two small fixes

---

backends/aptcc/apt-cache-file.cpp
backends/aptcc/apt-cache-file.h
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h
backends/aptcc/pk-backend-aptcc.cpp

new arguments: autoInst and preserveAuto
apt's markInstall can automatically try to resolve dependencies (incl.
recommends if applicable) without having the resolver deal with broken
dependencies at all. to that end it will mark dependencies of $package as
auto-install which gives them a slightly lower resolution score and the
auto flag (so they can be autoremoved).
To facilitate its use, the interface now calls toinstall twice: once
without autoInst to only mark explicitly wanted packages, and a second time
with autoInst to then also mark all needed dependencies. This is
specifically meant to allow or-relationships to resolve as desired.
e.g.
```
Package: foobar
Depends: foo|bar
```
with `pkcon install foobar bar` will explicitly mark foobar and bar and
thus prevent foo from getting …

aptcc: make toinstall more apt compliant

---

backends/aptcc/apt-cache-file.cpp
backends/aptcc/apt-intf.cpp

We can not accurately represent apt's held concept in PackageKit so to
mimic the intended behavior we simply exclude held packages from the
update listing. `pkcon update` and friends will not call update on held
packages, making them functionally held at their current version.
This has the added benefit that manually calling update
on the package will, just like install, break the version hold as the user
had to explicitly request the update (similar to apt's behavior on this).
fixed #120

aptcc: exclude held packages from update list

---

configure.ac
src/pk-engine.c
src/pk-transaction.c

ifdef cannot be used to determine if a C symbol is defined, as it’s
evaluated by the preprocessor, before symbols are parsed. Instead of
trying to detect whether polkit.h is suitably recent enough to define
its own auto-cleanup functions, just define our own in a different
namespace which is guaranteed not to collide with upstream.

Fix redeclaration of polkit autocleanup functions

---

configure.ac

Remove warnings as stated in https://autotools.io/forwardporting/autoconf.html

aptcc: fix ac_compile_ifelse

---

backends/aptcc/apt-intf.cpp

Through pkcon the user may supply package IDs directly. When we then look
for them through apt-pkg's FindGrp we may get a group iterator that is
not actually valid. The PackageList obtained from that group iterator
can contain random garbage so as a pre-condition to doing anything with the
packagelist we need to check if the group at hand is good.
If the group is not good any packages it may list or not will by default be
useless, so we should not iterate on them.
For the record: on apt 1.2.19 I actually have FindGrp come back as bad
but then give out a PackageList where the first iterator is both good and
not at the end, which seems a bit meh from an API behavior point of view
but somewhat within reason given the owning iterator (i.e. the group)
itself is in a bad state.

aptcc: Fix a crash when the user supplies a bad package ID

---

backends/aptcc/acqpkitstatus.cpp
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h

At the moment we always returned PK_STATUS_ENUM_UNKNOWN and it was hard
to keep track of what was happening.
Should improve issue #159.

[aptcc] Specify status when calling pk_backend_job_set_item_progress

---

client/pk-offline-update.c
data/packagekit-offline-update.service.in

While testing offline updates I noticed that reboot was scheduled twice when the packagekit offline update failed (see patch one for logs). Two fixes to make sure that either failure is returned or a reboot/shutdown in scheduled.

Failure handling

---

lib/packagekit-glib2/pk-progress-bar.c

This commit adds a conditional to check if the string of progress bar
and text input are NULL. The comparison needs to be executed with two
valid strings and not two NULL pointes. That's why the conditional has
an AND operator. Both needs to be an empty string or a valid string, not
a NULL pointer. This missing check is causing an error during the pkcon
execution. See the command output:
$ sudo pkcon repair
FIXME: need to call pk_progress_bar_start()
earlier![=========================]
Finished                      [=========================]
[=========================]
Testing changes               [=========================]
Finished                      [=========================]
After patching:
$ sudo pkcon repair
[=========================]
Finished …

pk-progress-bar: checks NULL strings inside pk_progress_bar_start () [v2].

---

src/pk-main.c

When the config file used by PackageKit daemon is not found, the
function `pk_util_get_config_filename()` returns a NULL pointer.
See:
https://github.com/hughsie/PackageKit/blob/master/src/pk-shared.c#L300
So, when `g_key_file_load_from_file()` is called, the variable
`conf_filename` is NULL and inside that function the `assert()` fails:
$ sudo packagekitd
(packagekitd:9133): GLib-CRITICAL **: g_key_file_load_from_file:
assertion 'file != NULL' failed
Segmentation fault
This PR introduces `g_printerr()` to redirect properly errors from pk-main.c to 
stderr.

pk-main: segfault when config file is not found [v3].

---

backends/aptcc/gst-matcher.cpp

The regex didn't work with gstreamer 1.0 input.
Try
pkcon what-provides 'gstreamer1.0(decoder-audio/mpeg)(mpegaudioversion=1)(mpegversion=1)(layer=3)'
to test.
Also, the second commit fixes a critical and no results that happen for the non-first queries. You can't deinit and then init again - it breaks gstreamer.
@ximion Please test this. I don't know much about this stuff. I think there's a way to request multiple codecs at once - how do you do that? I don't know and so I didn't test it. :)
Fixes #192.

aptcc: Fix installing gst codecs for gstreamer 1.0

---

backends/zypp/Makefile.am

PackageKit(using zypp backend) will crash when running
"pkcon get-updates" on 32-bit system.
Fix that by adding -D_FILE_OFFSET_BITS=64 to
libpk_backend_zypp_la_CPPFLAGS.
https://bugs.freedesktop.org/show_bug.cgi?id=101267

zypp: Fix stack smashing on 32-bit system

---

backends/aptcc/apt-intf.cpp
backends/aptcc/gst-matcher.cpp
backends/aptcc/gst-matcher.h

This is sent by pk-gstreamer-install.
We special-case this and use it to limit our search to 'amd64' packages
only.
In the future this should be extended to any 64 bit arch, I think.
---
Without this, we get:
```
laney@raleigh (master|…)> pkcon what-provides 'gstreamer1(decoder-audio/mpeg)(mpegaudioversion=1)(mpegversion=1)(layer=3)()(64bit)'
Getting provides              [=========================]         
Loading cache                 [=========================]         
Querying                      [=========================]         
Finished                      [=========================]         
laney@raleigh (master|…)>
```
And with it:
```
laney@raleigh (master|…)> pkcon what-provides 'gstreamer1(decoder-audio/mpeg)(mpegaudioversion=1)(mpegversion=1)(layer=3)()(64bit)' …
```

aptcc: Support "()(64bit)"

---

backends/alpm/pk-alpm-environment.c
backends/alpm/pk-backend-alpm.c
backends/alpm/pk-backend-alpm.h

If we set the proxy only once, the user won't be able to update it
without killing the daemon.

alpm: read the session proxy settings for each job

---

backends/zypp/pk-backend-zypp.cpp

fix commit bd7c947d62dd98e4e4a1a7dab713b00a99ce4776.

zypp: fix wrong variable name

---

data/packagekit-offline-update.service.in
data/packagekit.service.in

Today gnome-shell unconditionally tries to talk to PK, which doesn't
really do anything useful for ostree-managed systems (including rpm-ostree),
for example Fedora Atomic Workstation.
This is similar to https://github.com/rpm-software-management/dnf/pull/723

service: Use ConditionPathExists=!/run/ostree-booted

---

backends/aptcc/apt-intf.cpp

filename is being inserted into the argv array, this results in a double
free when we later free filename (first) AND then the argv array (second)

aptcc: do not crash on double free when updating a config file

---

configure.ac
src/pk-dbus.c

In case a PackageKit requesting process is not part of the user's login
session, we ask systemd-logind for the the user's "display" session
instead.
This fixes gnome-software "failed to set proxy" warnings.
https://bugs.freedesktop.org/show_bug.cgi?id=101281

Fix getting user session ID with D-Bus "user bus" model

---

backends/aptcc/apt-sourceslist.cpp

Most repositories will have a "deb" and a "deb-src" variant and
currently the description they offer is the same.

Include whether it's a Source repository

---

backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h
backends/aptcc/pk-backend-aptcc.cpp

users and vendors can "pin" a specific package version after the fact which
allows a specific version to be forced instead whatever the policy would
pick automatically. this sometimes constitutes a downgrade from an already
installed version. within an apt case these downgrades are resolved as
part of full-upgrades, equally within packagekit we'd inform the frontend
of downgrades via package emission. do this when get_updates is run.
the actual upgrade component of this is already implemented for quite a
while. the only thing that was missing is actually notifying the frontend
of the available downgrade.

aptcc: add support for downgrades as part of updates

---

backends/aptcc/acqpkitstatus.cpp
backends/aptcc/apt-intf.cpp

When the mirror method is used in apt 1.6 or newer, a mirror list is
downloaded prior to any package, causing PackageKit to crash after
casting its item to pkgAcqArchiveSane.
pkgAcqArchiveSane is a local workaround to expose some protected
stuff in pkgAcqArchive, so we first do a dynamic_cast to pkgAcqArchive
which will be nullptr if it is not a pkgAcqArchive and then cast it
statically to pkgAcqArchiveSane.
Bug-Ubuntu: https://launchpad.net/bugs/1754265
CC @ximion

aptcc: Not all downloads have to be packages

---

backends/dnf/pk-backend-dnf.c

Requires: libdnf-0.13.0+
G object DnfPackageSet in libdnf was replaced by c++ class therefore
g_object_unref cannot be used anymore, but the new dnf_packageset_free has to be
used instead.

Reflect latest changes in libdnf

---

backends/dnf/pk-backend-dnf.c

It should disable packages from disabled modules.
The patch requires libdnf-0.15.0

Allow module filtering

---

backends/dnf/pk-backend-dnf.c

Libdnf API has changed and the function takes an additional argument: platformModule.
It's set to NULL to trigger platform module auto-detection based on /etc/os-release.

Add additional argument to the dnf_sack_filter_modules() call.

---

contrib/command-not-found/PackageKit.sh.in

Check that the client command is executable before executing it,
otherwise you get:
$ foo
-bash: /usr/libexec/pk-command-not-found: No such file or directory
Signed-off-by: Adam Jackson <ajax@redhat.com>

command-not-found: If we get uninstalled while running, don't  complain

---

backends/aptcc/apt-intf.cpp

This commit removes a duplicate call inside providesCodec() function.
When cancel is active, the loop call tries to delete 'matcher' and after
breaks the loop. But, the function will tries to delete 'matcher' again
at the end.
Signed-off-by: Julio Faracco <jfaracco@br.ibm.com>

aptcc: removing duplicate delete call.

---

backends/aptcc/apt-intf.cpp

ver.Arch() was accessed even if ver.End() was true and ver thus
pointed to invalid memory, causing undefined behavior and likely
crashes, such as the Ubuntu bug below.
Bug-Ubuntu: https://bugs.launchpad.net/bugs/1790671

aptcc: Fix invalid version dereference in AptInf::providesCodec()

---

lib/packagekit-glib2/pk-progress-bar.c

Also, fd==0 is unlikely, but valid. Do the right thing in finalize().

Never assert when an interactive TTY is not available

---

backends/aptcc/apt-intf.cpp

aptcc wrongly only tried the multi-arch names with architecture
included if multi-arch was enabled. dpkg however always uses arch-
qualified names - otherwise it would have to rename half its database
after enabling / disabling multi-arch.

aptcc: Always try multi-arch lookups for lists

---

client/pk-offline-update.c

Do the setlocale stanza in main() to correctly set up gettext.
Fixes: https://github.com/hughsie/PackageKit/issues/280
(Completely untested, just copied the gettext stuff from pk-main.c)

offline update: Fix translations to show up

---

backends/dnf/pk-backend-dnf.c
src/pk-shared.c
src/pk-shared.h

If a user ignores gnome-software install notifications and never applies
offline updates, we would keep downloading new rpms and never delete the
old ones from the cache.
This commit fixes this.
The cache cleanup strategy is to wait until we've finished downloading a
new offline update, and then clean up any rpms from the cache that the
newly downloaded update doesn't need.
https://bugzilla.redhat.com/show_bug.cgi?id=1306992

dnf: Avoid offline updates cache growing unchecked

---

lib/python/packagekit/Makefile.am

This will fix compilation in system where only the "python3" executable exists

lib/python/packagekit/Makefile.am: Use the detected PYTHON version

---

configure.ac
src/Makefile.am
src/pk-dbus.c
src/pk-engine.c

One of our downstream maintainers forgot to submit this for inclusion it seems so here it is.
Closes: https://bugs.gentoo.org/620948
Signed-off-by: Ettore Di Giacinto <mudler@gentoo.org>

Add elogind support

---

src/pk-transaction.c

We should return directly while failing to set transaction’s state
because it’s going backwards. That’s exactly what Pk did previously.
Fixes 2807cbf8

transaction: Return directly when its state is going backwards

---

backends/aptcc/apt-messages.cpp
backends/aptcc/apt-messages.h

The aptcc `show_errors()` function doesn't return anything, but was declared with a `bool` return type. This PR changes the function to a `void` return type. The `bool` that was supposedly returned by the function wasn't used anywhere.
I found this issue when investigating [this crash][1], which seems to be a problem with temporary objects being destructed in wrong order in an optimized build. Fixing the return type of `show_errors()` also seems to have fixed this crash. I'm suspecting the optimizer got confused by the invalid return and generated invalid code, but I can't really be sure this is really the root cause for the crash.
But be that as it may, fixing the return type of the `show_error()` function makes the code more correct in any case.
[1]: …

aptcc: Use correct return type in show_errors()

---

backends/zypp/pk-backend-zypp.cpp

Not the prettiest solution, but since zypper checks for `dup` argument the same way when notifying the user about proper update command, this is the most distro-agnostic way I could do this.

zypp: Switch to doUpgrade solver when required by distribution

---

backends/aptcc/apt-intf.cpp
configure.ac

This implements APT frontend locking, which prevents other programs
from stealing the dpkg lock in race conditions where apt(cc) has to
release the lock in order to run dpkg.
Bug-Ubuntu: https://bugs.launchpad.net/bugs/1795614

aptcc: Implement frontend-locking

---

docs/api/PackageKit-docs.sgml
docs/html/pk-using.html

This contributes to #276. I would like to write documentation in PackageKit-docs.sgml but I have no clue how to create external links in docbook (I tried both `<xref>` and `<link>`).

docs: Improve the 'using' documentation with a link to API

---

backends/aptcc/acqpkitstatus.cpp

the previous code paths only covered
- Hit (aka the server responded with not-modified or somesuch code)
- Ign (aka the server 404s or somesuch indicating the repo doesn't exist)
but ignored
- Get (aka code 200 and data was downloaded)
this resulted in repos which actually had updates available (hence the
file change and need for download) not being reported in `pkcon refresh`
output at all.
::Done acquire updates now also cause a repo detail to get added so
pkcon can show the repo as [enabled] when running `pkcon refresh`.

aptcc: also generate a repo detail when a download happened (and finished)

---

backends/dnf/dnf-backend-vendor-mageia.c

With Mageia 7, armv5tl has been removed and aarch64 has been introduced.
Thus, we want to make sure aarch64 repositories are marked as supported
and remove armv5tl from the supported arches list.

dnf: Replace armv5tl with aarch64 for Mageia repo configuration vendor

---

client/pk-offline-update.c
configure.ac

These landed in plymouth git yesterday to implement
https://wiki.gnome.org/Design/OS/BootProgress
Using the new API conditionally is tricky as it's command line API;
enterprise distros that don't have new enough plymouth should probably
just revert this commit.

offline update: Use new plymouth "system-upgrade" and "reboot" modes

---

backends/aptcc/Makefile.am
backends/aptcc/pk-debconf-helper.c
backends/aptcc/pk-debconf-helper.service.in
backends/aptcc/pk-debconf-helper.socket.in
configure.ac
lib/packagekit-glib2/pk-client-helper.c
lib/packagekit-glib2/pk-client-helper.h
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-client.h

Introduce support for a socket-activated client helper for aptcc. This solves a problem where the current client helpers are children of the client starting the transaction and potentially bound to the client's lifetime; so if the client is exited early, while the transaction is still running, no debconf prompts would be shown.
A socket-activated helper solves this problem by making sure we only ever run one helper as a systemd user service.
This change is incompatible with the debconf-kde hacks, I'm not sure what to do about those yet.

Socket-activated client helper

---

backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h
backends/aptcc/pk-backend-aptcc.cpp
client/pk-console.c

Output of 'pkcon get-updates' command is changed to reflect more closely what would actually be updated, installed, removed or obsoleted during update, but it may require to modify users of this command to not just install everything from output of this command, including removed and obsoleted packages, similarly to how 'pkcon update' is updated in these changes.

aptcc: improve support of obsoletes during updates

---

backends/dnf/pk-backend-dnf.c

Work around a modularity upgrade bug by resetting the libgit2 module
when upgrading to F31. This depends on new libdnf API from
https://github.com/rpm-software-management/libdnf/pull/822
https://bugzilla.redhat.com/show_bug.cgi?id=1762751

dnf: Reset libgit2 module when upgrading to F31

---

backends/zypp/pk-backend-zypp.cpp

This addresses https://github.com/hughsie/PackageKit/issues/354 and matches the behavior of zypper command line.
Example searches to test: `mozillafirefox` (MozillaFirefox), `playonlinux` (PlayOnLinux).

Zypp: Make name/description search case insensitive

---

po/ko.po

Korean language has different sentence structure than English so parameters should have reversed order.
https://github.com/hughsie/PackageKit/blob/8118cee4d016f237408fd4b0752200d4f9b0bbb7/po/ja.po#L643
Japanese version of translation does same thing because Japanese has same structure with Korean.

[L10n] Correct Korean translation

---

backends/dnf/pk-backend-dnf.c

This change has the potential to break other distributions
using the DNF backend, and exclusively applies to Fedora.
This is better maintained as a downstream-only patch in Fedora.
This reverts commit 6dc4d503cfab4c0270924ddf8acfefb4f06d47fa.
This is an alternative to #361. I'd personally prefer this to be merged.

Revert "dnf: Reset libgit2 module when upgrading to F31"

---

backends/dnf/Makefile.am
backends/dnf/dnf-backend-vendor-rosa.c
configure.ac

Starting with the ROSA Linux 2019.1 platform, ROSA Linux will use
DNF as the PackageKit backend.

dnf: Add vendor configuration for ROSA Linux

---

backends/dnf/dnf-backend-vendor-openmandriva.c

OpenMandriva has added a rolling release variant of the distribution and
added new repos for allowing users to configure for the rock (stable),
rolling (stable beta), and cooker (devel) content.
In addition, the architectures have been slightly revised, as
an AMD Ryzen optimized variant was added and the 32-bit ARM variant
switched to armv7hnl (requiring NEON extensions).

dnf: Fix OpenMandriva vendor for rolling variant and new architectures

---

backends/dnf/pk-backend-dnf.c

We already call dnf_utils_refresh_repo_appstream() on startup, but only as
required. Remove the unconditional copy to speed up gnome-software startup.

Do not trigger an inotity event when the AppStream XML data is unchanged

---

lib/packagekit-glib2/meson.build

This restores the original build of the GIR with  automake.

meson: Add missing header files to gnome.generate_gir()

---

backends/aptcc/apt-intf.cpp
backends/aptcc/apt-messages.cpp

Previously aptcc would report some warnings as errors. This way,
it will drop any warning if there is no error. This matches the
behavior of python-apt.
As a bonus, we also log the entire message as a warning to the
journal.
This obsoletes #295

aptcc: Only report errors if there are errors

---

backends/alpm/pk-alpm-config.c

Currently packagekit exits on startup when the option was specified:
packagekitd[18705]: Failed to initialize alpm: using
/etc/PackageKit/alpm.d/pacman.conf:
/etc/PackageKit/alpm.d/pacman.conf:8/etc/pacman.conf:41unrecognised
directive 'DisableDownloadTimeout'
This change adds support for DisableDownloadTimeout and fixes the error.

alpm: Fix config parsing for DisableDownloadTimeout

---

backends/alpm/pk-alpm-transaction.c

According to upstream doc [1], total being -1 is a signal for download
initialized. We should avoid giving unnecessary assertion failures for every
file download.
[1]
https://git.archlinux.org/pacman.git/tree/lib/libalpm/dload.c?id=e76ec94083235ddc5510ab57b7c2bc12a1d34e8a#n134

alpm: Fix assertion failures for download start signals

---

.travis.yml

Rather than having them run one after the other, it makes sense
to have them run independently in parallel. This also makes it
clearer in the job logs, since now each build is an independent
CI job.

ci: Parallelize Fedora and Debian PackageKit CI jobs

---

backends/alpm/meson.build
backends/alpm/pk-alpm-environment.c
meson.build

There are several shortcomings and errors in building ALPM using meson.
- update of the library version to the latest stable version
- changing `confdir` which does not exist in the meson configuration to`sysconfdir`.
```sh
packagekit/backends/alpm/meson.build:3:0: ERROR: Tried to access unknown option "confdir".
```
- commas were missing in several places
```sh
packagekit/backends/alpm/meson.build:35:4: ERROR: Expecting rbracket got string.
packagekit/backends/alpm/meson.build:47:2: ERROR: Expecting rparen got string.
```
- project name and version declarations were missing which were default in AC_INIT, I added appropriate constant variables.
```sh
../packagekit/backends/alpm/pk-alpm-environment.c: In function ‘pk_alpm_environment_initialize’: …
```

Meson builds for ALPM, patches

---

backends/meson.build
meson_options.txt

PackageKit has permitted building multiple backends with Autotools,
and there's no reason to forbid this with Meson, especially as there
are still multiple options in use by some Linux distributions.
Fixes #383.

backends: Allow multiple backends to be built with Meson

---

backends/alpm/pk-alpm-update.c

Generally, refreshing databases without a full system update isn't desirable behaviour on systems managed by alpm and can lead to partial updates and related breakage.
Making it a nullop without force prevents the possibility of breakage in normal usage while leaving the ability for users who actually want to attempt a potentially unsafe operation to attempt it.

Make pk_alpm_update_database a nullop without force

---

backends/alpm/pk-alpm-config.c
backends/alpm/pk-alpm-config.h
backends/alpm/pk-alpm-update.c
backends/alpm/pk-backend-alpm.c

This prevents updating the system syncdbs without updating packages,
which often leads to undesirable behaviour on most alpm-based distros.

alpm: use separate alpm_handle_t for updates

---

backends/alpm/pk-alpm-transaction.c

When the target name is blank, the callback is generally for the
transaction in general and not for an unknown item. This handles
all instances where libalpm currently emits a progress callback with a blank
name.
Fixes #173.

alpm: handle blank target name for progress cb

---

backends/aptcc/meson.build

I was getting the following error while trying to use the aptcc backend since the meson port.
```
Failed to load the backend: opening module aptcc failed : backends/aptcc/libpk_backend_aptcc.so: undefined symbol: forkpty
```
This was explicitly linked in the old Makefiles and seems to have been missed in the meson port:
https://github.com/hughsie/PackageKit/blob/3de80c8eb0dca0b57a5dbdca20e754a7de7c053a/backends/aptcc/Makefile.am#L29

aptcc: Add libutil to linker args

---

backends/aptcc/apt-intf.cpp

It seems that the other backends use this method to format the proxy strings where necessary. Since this proxy string is put in the `http_proxy` envvar for the aptcc backend, this needs to be in the correct `http://username:password@hostname:port/` format.

aptcc: Use pk_backend_convert_uri on proxy settings

---

meson.build

Currently, PackageKit builds spew implicit function declaration warnings
for usage of `realpath(3)`, which is gated by a `_DEFAULT_SOURCE` define.
Since we expect it to be usable, let's add the definition so it is.

meson: Add _DEFAULT_SOURCE to ensure "default" functions are available

---

backends/dnf/meson.build
backends/dnf/pk-backend-dnf.c
tests/ci/Dockerfile-fedora

Historically, the backend has internally determined its setup with
static values. However, we generally want PackageKit to load all
repositories defined in all repository directories that DNF normally
searches, since it is not guaranteed to be in `/etc/yum.repos.d` and
DNF supports multiple repository configuration paths.
We also need the vars to be loaded so that repository definitions
that rely on more than the built-in vars will work.
This bumps our dependency for libdnf to 0.43.1, as we're using APIs
introduced in this release.

dnf: Load all the repos and vars directories

---

src/pk-main.c

This reverts commit 0c84d71509e851db20445c747529bd7d3724f081.
This broke the end session dialog in GNOME Shell.
I thought I had that fixed by changing GNOME Shell to autostart
PackageKit when it is not already running:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1104
But turns out, there are more problems. The update fails if the user has
used dnf since PackageKit last quit, a scenario I did not test. It also
results in GNOME Software getting confused about what software is
installed and what software is not. The issues are discussed here:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1227#note_784327
It's still desirable to shut down automatically, but it requires more
planning. And shutting down GNOME Software itself is frankly more
important, since it uses …

Revert "Shutdown the daemon on idle by default"

---

backends/alpm/meson.build
backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-update.c
backends/alpm/pk-alpm-update.h

Updating without synchronising databases is like `pacman -Syu` without the `pacman -Sy`:
1) It's normally not possible
2) That leaves the system in an inconsistent state

alpm: synchronise syncdbs on update

---

client/pk-console.c

In case a user asks pkcon to install an already installed package,
so far we returned with:
Fatal error: The packages are already all installed
(detailed string provided by the backend)
and retval 7.
Taking pkcon's manpage into account, retval 5 is more appropriate:
RETURN VALUES
0
Success
5
Nothing useful was done.
7
The transaction failed, see the detailed error for more information.

pkcon: exit with retval 5 if no packages needed be installed

---

backends/dnf/dnf-backend-vendor-opensuse.c
meson_options.txt

openSUSE now ships the DNF backend for PackageKit.

dnf: Add vendor configuration for openSUSE

---

contrib/command-not-found/meson.build

Otherwise you end up with `libexec/...` in `PackageKit.sh` instead of `/usr/local/libexec/...`.

Fix setting libexecdir for command-not-found helper.

---

backends/test/helpers/meson.build
backends/test/meson.build

During the conversion from Autotools to Meson, this part was accidentally
lost, which makes the test backend not work quite right.
This change installs the missing files for the test_spawn part of the
test backend.

test: Install required helper files

---

backends/aptcc/apt-intf.cpp
src/pk-transaction.c

Vaisha Bernard discovered that PackageKit incorrectly handled certain
methods. A local attacker could use this issue to learn the MIME type of
any file on the system. (CVE-2020-16121)
https://bugs.launchpad.net/bugs/1888887
Sami Niemimäki discovered that PackageKit incorrectly handled local deb
packages. A local user could possibly use this issue to install untrusted
packages, contrary to expectations. (CVE-2020-16122)
https://bugs.launchpad.net/bugs/1882098

Security bugs CVE-2020-16121 and aptcc specific CVE-2020-16122

---

meson.build
src/pk-main.c

This makes sure that the main process won't get SIGTERM on shutdown,
for example timed exit after idling for a while. This fix the problem
that libzypp fails to clean up some temporary files when packagekitd
quits.

main: notify the service manager when it's beginning to shutdown

---

src/pk-dbus.c

Fixes https://github.com/hughsie/PackageKit/issues/436

Do not crash when calling pk_dbus_get_uid() before D-Bus is setup

---

backends/dnf/pk-backend-dnf.c

Some distributions (particularly rolling release distributions)
prefer that normal "upgrade" actions actually trigger the distupgrade
method in the package manager. This change enables that if the
installed  distribution release package specifies that this
behavior must occur.

dnf: Add support for coercing upgrade to distupgrade

---

backends/alpm/pk-alpm-config.c
backends/alpm/pk-alpm-databases.c
backends/alpm/pk-alpm-install.c
backends/alpm/pk-alpm-remove.c
backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-transaction.c
backends/alpm/pk-backend-alpm.c

The current variable name `errno` results in a name clash when building the ALPM backend.
Renaming it to `alpm_err` resolved the issue.

Rename errno to alpm_err to avoid name clashes

---

lib/packagekit-glib2/pk-enum-types.c.template
lib/packagekit-glib2/pk-enum-types.h.template

Avoid using full filename in comments as that can be different on
different arches if the build directory differs, leading to multilib
conflicts. Instead just use @basename@, which is always the same.
https://bugzilla.redhat.com/show_bug.cgi?id=1915259

Fix multilib conflicts in generated pk-enum-types.h

---

backends/alpm/90-packagekit-refresh.hook
backends/alpm/meson.build

This allows refreshing the PackageKit cache after updating or installing
a package using pacman.
fixes #458

alpm: Add post transaction hook

---

src/pk-transaction.c

Some distros regularly push updates of tens of thousands of packages,
causing users to run into this "too many packages" error. This is not
really an error, it's just that the sanity check didn't anticipate that
the world might be insane. :) Let's remove it to avoid these issues.

Remove large transaction size sanity check

---

src/pk-transaction.c

They stopped being used in commit ac5c8660a8.
This stops a load of compiler warnings.

pk-transaction: Remove a load of unused variables

---

lib/packagekit-glib2/pk-client.c

See the commit messages for details.
This may fix https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1118 (but I’m not entirely certain about it).

Fix hangs in packagekit-glib2 client if daemon crashes

---

lib/packagekit-glib2/pk-client.c
src/pk-backend-spawn.c
src/pk-engine.c
src/pk-transaction.c

PackageKit methods may be called in all sorts of contexts — as a result of an explicit user action, or as a background operation. Sometimes PackageKit will need to check a polkit action, and sometimes this will result in a polkit password prompt. Showing those prompts unexpectedly for background operations is quite surprising for users; plumb through the right D-Bus call flags and `PkTransaction` hints to try and ensure that they are only shown for PackageKit methods which are called as a result of explicit user action.
I have tested that this compiles, but no further than that.
See also:
* https://gitlab.gnome.org/GNOME/gnome-software/-/issues/582
* https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/726 (this PR is complementary, but independent)

Fix use of POLKIT_CHECK_AUTHORIZATION_FLAGS_ALLOW_USER_INTERACTION

---

backends/dnf/dnf-backend.c
backends/dnf/dnf-backend.h
backends/dnf/pk-backend-dnf.c
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-enum.c
lib/packagekit-glib2/pk-enum.h
lib/packagekit-glib2/pk-package.c
lib/packagekit-glib2/pk-package.h
src/pk-backend-job.c
src/pk-backend-job.h
src/pk-transaction.c

The DNF backend can read update severity, beside the update type.
This change passes the value to the PkPackage object, thus the caller
can read it. It's set when the caller asks for the updates.
----------------------------------------------------------------------
This change has incorporated notes from https://github.com/hughsie/PackageKit/pull/474

PkPackage: Add update severity property

---

backends/dnf/pk-backend-dnf.c
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-details.c
lib/packagekit-glib2/pk-details.h
src/pk-backend-job.c
src/pk-backend-job.h
src/pk-transaction.c

This consists of two changes:
* the first changes the dnf backend to use the install size, instead of the package size, in the PkDetails; two reasons for it: a) the documentation mentions it'll be an install size for installed packages; b) the user is more interested in the install size than the package size;
* related to the previous point, add "download-size" into the PkDetails - that removes the ambiguity of the PkDetails::size whether it's installed or package size, because there's no property about it in the PkDetails (one can figure out whether the package is installed or not, but it means running additional commands, which are unnecessary). It also can provide an information whether the package is ready to be installed (its download size is 0). …

Install size versus download size in PkDetails

---

backends/aptcc/apt-intf.cpp
docs/api/PackageKit-docs.sgml
docs/html/pk-bugs.html
docs/html/pk-download.html

This PR contains a couple of minor URL fixes in the source tree to account for the move of the PackageKit repository to its own GitHub organization.

GitHub URL fixes

---

src/meson.build

The packagekit-direct executable couldn't use backends that use
functions from pk-backend-spawn.h, e.g., the APT backend:
Failed to load the backend: opening module aptcc failed : /usr/lib64/packagekit-backend/libpk_backend_aptcc.so: undefined symbol: pk_backend_spawn_set_name

packagekit-direct: make backends that use pk-backend-spawn work (#477)

---

src/Makefile.am

(This fixes the same issue as the cited commit, but for
PACKAGEKIT_1_1_X with autotools.)
In case you still accept fixes for PACKAGEKIT_1_1_X with autotools, here is the fix for the same issue (fixed in master). I have got it ready because it made my life simpler with a kind of bisect of previous versions and testing them with `packagekit-direct`.
commit 40cd9727d79683e85fcbd8e1ac74ce06a933d3cf
Author: Ivan Zakharyaschev <imz@altlinux.org>
Date:   Thu May 20 22:43:08 2021 +0300
packagekit-direct: make backends that use pk-backend-spawn work (#477)
The packagekit-direct executable couldn't use backends that use
functions from pk-backend-spawn.h, e.g., the APT backend:
Failed to load the backend: opening module aptcc failed : /usr/lib64/packagekit-backend/libpk_backend_aptcc.so: undefined …

packagekit-direct: make backends that use pk-backend-spawn work (#477, but for PACKAGEKIT_1_1_X with autotools)

---

lib/packagekit-glib2/pk-client.c
src/pk-transaction.c

The PkClient operates in two stages. The first is an "active" stage,
which makes one or more D-Bus calls. The second is a "passive" stage,
when it is waiting for the "Finished" D-Bus signal from the daemon.
The cancellation can come in any time. This change keeps the cancellation
up to the D-Bus calls during the first stage and actively stops the waiting
during the second stage.
As the GCancellable is cancelled in a different thread, and any D-Bus call
is also done and its result delivered in that thread default main context,
rather than in the main context when the PkClientState had been created,
the PkClientState is switched to a GObject descendant, to be able to benefit
from the GWeakRef, which can avoid use-after-free easily.
The GDBusProxy callbacks can be schedules in the middle of …

PkClient: Improve thread safety on an operation cancellation

---

backends/dnf/meson.build
backends/dnf/pk-backend-dnf.c

This provides significant performance improvement when checking
package advisories.
Do not bump version dependency on libdnf, rather check during
the configure phase whether the function exists and conditional-compile
related code accordingly.
This depends on https://github.com/rpm-software-management/libdnf/pull/1252

dnf: Use 'hy_query_get_advisory_pkgs', if available

---

lib/packagekit-glib2/pk-client.h
lib/packagekit-glib2/pk-task.c

To make it easier to know, in the code, that the user declined
the interaction on the task and react on it properly, rather than
checking a generic error code and the error message, which can
eventually change in the future.

pk-task: Add specific error code when user declined interaction

---

data/packagekit.service.in

This commit keeps packagekitd from thinking the system is perpetually offline and instead waits for the network services to become available before it completely activates. This does not slow the boot process.
This is in reference to #336

wait until online to activate systemd service

---

client/pk-console.c
docs/api/PackageKit-sections.txt
lib/packagekit-glib2/pk-offline.c
lib/packagekit-glib2/pk-offline.h
lib/packagekit-glib2/pk-test-daemon.c

This partly reverts commit 9b7e083cf849c4ed4d66fe32250f1615ab577d94.
The offline update/upgrade triggers do need the user interaction, to
get the credentials from the polkit, otherwise the trigger cannot
do its job.
Closes https://github.com/PackageKit/PackageKit/issues/504

pk-engine: Always allow user interaction for offline update/upgrade

---

backends/zypp/pk-backend-zypp.cpp

Code introduced by commit c45e0f22df682 is strange.
Depending partly on uninitialized array values when an array
is not even needed, and also using the values both as enum
and as some kind of existence check.
cc: @JonathanKang

zypp: Fix package installation using undefined data

---

backends/alpm/pk-alpm-packages.c
backends/alpm/pk-alpm-search.c
backends/alpm/pk-alpm-update.c
backends/alpm/pk-backend-alpm.c
backends/alpm/pk-backend-alpm.h

We create a separate database when we refresh to make sure we don't
leave the system's at an odd state. In turn, this leaves the current
database at an odd state.
This makes our query operations use our database instead of the system's
while it's alive, so other transactions also can know about the
information we fetched from our remotes.
Also stop leaking the temporary database.
Fixes #491

alpm: Offer the database we create when updating

---

backends/dnf/pk-backend-dnf.c

PackageKit has been correctly recording transaction information in
the history database for some time now, so there is no reason keep
blocking support for this.
Fixes #201

dnf: Add support for autoremove flag when removing packages

---

backends/alpm/pk-alpm-sync.c
backends/alpm/pk-alpm-update.c
backends/alpm/pk-alpm-update.h

We were just checking filenames, now using alpm_dep_from_string() we
make follow the pkgname<1.0 kind of notation.

alpm: Support replaces with version expressions

---

backends/dnf/pk-backend-dnf.c

This follows from the documentation, and adjusts to the behavior of other backends.
For more info see https://github.com/PackageKit/PackageKit/issues/527

DNF backend: Searches by name and package details should be case insensitive.

---

backends/aptcc/apt-cache-file.cpp
backends/aptcc/apt-cache-file.h
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-utils.cpp
backends/aptcc/apt-utils.h
backends/aptcc/pk-backend-aptcc.cpp
backends/aptcc/pkg-list.cpp
backends/aptcc/pkg-list.h

Hi!
As far as I could test, this patchset, which features quite a bit of annoying refactoring, resolves the issue outlined in https://github.com/PackageKit/PackageKit/issues/450 (kernel updates marked as manually installed while they were in fact dragged in by an update).
While looking into the aptcc code after such a long time, I also quickly discovered why doing that is not at all my favourite activity ;-)
In all my tests the new code behaved correctly when updating as well as performing any other package management activities, but of course, more testing is helpful.
@dantti Can you maybe have a look at this?

aptcc: Keep automatic state from previously resolved transactions when applying them

---

backends/aptcc/apt-cache-file.cpp
backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h
backends/aptcc/pk-backend-aptcc.cpp

This Pull Request will fix a few bugs relating to installing and searching packages when using the `aptcc` backend, namely:
- When installing a package that is not the latest available version, the backend will either treat the package as does not exist or install a version that is different than requested
- When downgrading a package, the backend will incorrectly reinstall the package using the current version instead of performing a downgrade to the specified version
- When searching/resolving a package or package ID, the backend will fail to list all the available versions or just fail to list anything

aptcc: fix serveral bugs relating to installing and searching packages

---

backends/nix/meson.build
backends/nix/nix-lib-plus.cc
backends/nix/nix-lib-plus.hh
backends/nix/pk-backend-nix.cc

Try to reflect the changes made before ~~https://github.com/NixOS/nix/commit/ffe155abd36366a870482625543f9bf924a58281~~ https://github.com/NixOS/nix/commit/69c6fb12eea414382f0b945c0d6c574c43c7c9a3. Without the change the build fails with:
```
In file included from ../backends/nix/nix-lib-plus.cc:27:
../backends/nix/nix-lib-plus.hh:20:107: error: 'string' does not name a type; did you mean 'nString'?
20 | bool createUserEnv(EvalState & state, DrvInfos & elems, const Path & profile, bool keepDerivations, const string & lockToken);
|                                                                                                           ^~~~~~
|                                                                                                           nString
```
Tested compilation on …

Nix: fix build with Nix 2.8.0

---

lib/packagekit-glib2/pk-client.c

`pk_client_init()` sets the default value to `G_MAXUINT` but the
`GParamSpec` setup didn’t also use that value.
This probably introduces no functional changes, but it makes the code
not contradict itself.

pk-client: Fix default value of cache-age property

---

backends/zypp/pk-backend-zypp.cpp

Closes #325 
Currently if a package is locked on ZYpp PackageKit ignores the lock and silently updates or installs it.
This PR adds a check if a package is locked a before adding it to the packages to be updated list.
Implementation and comment in code was inspired by the one in aptcc backend
https://github.com/PackageKit/PackageKit/blob/9339249866d44f06d713e92f2abf90b470b5deb3/backends/aptcc/apt-intf.cpp#L1303-L1308

zypp: ignore locked packages

---

src/org.freedesktop.PackageKit.Transaction.xml

docs: Fix some XML typos in the Transaction interface documentation

---

src/pk-main.c

It doesn’t add one itself (by contrast, `g_message()` and friends do add
one).

pk-main: Add newline on g_printerr() calls

---

src/pk-main.c

As suggested by Matthias on
https://github.com/PackageKit/PackageKit/pull/559#issuecomment-1173005774

pk-main: Mark some early-start error messages as translatable

---

policy/org.freedesktop.packagekit.policy.in

The documentation says that unprivileged users can install signed packages. This has not been true since d462e2e62d700d0d29c41a8d9c4bbffbe99339ff from 2007. The comment is extremely stale. Fix it to match reality.

Fix documentation of package-install policy

---

README

As I was able to gather from #411 the website used to be a redirect to https://www.freedesktop.org/software/PackageKit/. As the website at packagekit.org is now defunct and just shows a Google Domains expiry notice, I think it would be beneficial to change the URL referenced in the README file.

Update documentation URL in README

---

backends/aptcc/apt-intf.cpp
backends/aptcc/apt-intf.h

This refers to #571 .
As suggested by @ximion, I created a patch that detects if the --force-conf* option is set and if it is, PackageKit does not change it.
This allows the admin to set a system-wide default behavior for config file updates, which is also used by PackageKit.
I also looked  at the [dpkg code](https://github.com/guillemj/dpkg/blob/1e61d9416719b628ec0e93ced10fe4c1f38ef105/src/main/configure.c#L123)  to find out what these options really do, because the documentation on them is confusing.
First of all, these settings are not affected by "DEBIAN_FRONTEND=noninteractive", which is only used for (post install) configuration prompts (accept eula, setup database...).
All three options disable the interactive prompt for configuration files.
--force-confdef **ignores …

aptcc: Detect if apt system settings specify --force-conf* options

---

backends/alpm/pk-alpm-config.c

~Note that I have not tested this,~ just looked at 
https://github.com/PackageKit/PackageKit/blob/7e700e2177ca3f84ea5a2978cdf687179b3445a9/backends/alpm/pk-alpm-config.c#L1017
and 
https://github.com/devkitPro/pacman/blob/49b08fa9d14a9cc06f01c624c644cb987ce97642/lib/libalpm/alpm.h#L1732
and thought it was a copy paste error.

Fix issue #342 core-dump using alpm backend with hookdirs config set

---

src/pk-engine.c

This was broken in commit c8b531.
This should fix errors like the following when calling `SetProxy()`:
```
PackageKit-WARNING **: 14:50:25.673: failed to set proxy: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._pk_2dengine_2derror_2dquark.Code3: setting the proxy failed: failed to get the uid
```

pk-engine: Fix checking D-Bus caller details when setting proxy

---

client/pk-monitor.c
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-progress.c
lib/packagekit-glib2/pk-progress.h
src/org.freedesktop.PackageKit.Transaction.xml
src/pk-dbus.c
src/pk-dbus.h
src/pk-shared.c
src/pk-shared.h
src/pk-transaction.c

Hi!
I was investigating https://github.com/PackageKit/PackageKit/issues/586 and thought that it would be incredibly useful for `pkmon` to show who has created a transaction. I also remembered that we had a feature once to add the client command-line to the transactions database, but I couldn't find that anywhere in the DB. So I looked into it and in commit https://github.com/PackageKit/PackageKit/commit/9912d52ba7c87bfb5a992e1c4914c188dc546c22 the cmdline feature was limited to only a few roles in the name of performance - however, at the time this code is run, the transaction role is UNKNOWN, so the cmdline will never be set and the feature will never be used.
So, I restored support for the lost functionality, and also added a new transaction property, `ClientPid` (calling it just `Pid` …

Add client PID as transaction property and store its cmdline in db again

---

client/pk-console.c

The `pk_progress_bar` `padding` value was set to 30, making that the minimum width for status text displayed next to a progress bar. But one of the status texts displayed in English during `refresh` is "Downloading repository information", which is 34 characters. As a result, the output ends up looking like this:
```console
$ pkcon refresh force
Refreshing cache              [=========================]         
Loading cache                 [=========================]         
Downloading repository information[=========================]         
Loading cache                 [=========================]         
Downloading repository information[=========================]         
Loading cache                 [=========================]         
Downloading repository …
```

pkcon: Widen progressbar text area

---

src/pk-transaction.c

This seems to have been forgotten when the property was added.

pk-transaction: Add support for getting the RemainingTime property

---

backends/dnf/meson.build
backends/dnf/pk-backend-dnf-common.c
backends/dnf/pk-backend-dnf-common.h
backends/dnf/pk-backend-dnf-refresh.c
backends/dnf/pk-backend-dnf.c
contrib/PackageKit.spec.in

Run pk_backend_refresh_repo in a new process to avoid keeping libdnf memory leaks.
This is not a real PR, I do not expect this to be merged.  I understand that running complex code in a process forked from a threaded process is not safe.
This PR is instead intended as a suggestion / request to move pk_backend_refresh_repo into a new helper application, and to fork&&exec that helper from pk_backend_refresh_cache_thread.
While reviewing packagekitd memory use on Fedora, I saw constant growth of memory use every time repo metadata was refreshed (easily demonstrated by running `pkcon refresh force` repeatedly.  Running packagekitd under valgrind appeared to locate numerous memory leaks, most of which were under libdnf's dnf_repo_update().  The number of unique leaks detected makes fixing them …

Run pk_backend_refresh_repo in a new process

---

backends/apt/meson.build
backends/nix/meson.build
backends/slack/meson.build
backends/slack/tests/meson.build
backends/zypp/meson.build
meson.build

This removes ad-hoc flag passing from backends that are written in C++.

Pass -DPK_COMPILATION to the C++ compiler too.

---

src/pk-main.c

This reverts commit dca1f5b2508a4632d0b9fefab771a5a9caf83a5c.
Which reverted commit 0c84d71509e851db20445c747529bd7d3724f081, which reverted commit c6eb3555ec5b41e988c111d276764d55fb83bda3.
Fixes #460.  High memory usage was also reported on Redhat's bug tracker back in 2016, and a couple more times since:
https://bugzilla.redhat.com/show_bug.cgi?id=1354074 
https://bugzilla.redhat.com/show_bug.cgi?id=1854875 
https://bugzilla.redhat.com/show_bug.cgi?id=1896964
The memory usage of packagekitd without the timeout has been observed growing well beyond half a GiB. On two of my own machines running Fedora 36 as I write this, 537 MiB and 696 MiB. 
As I understand it, this timeout causes some slightly surprising behavior when users mix command line dnf upgades with GUI PackageKit upgrades, and …

Revert "Revert "Shutdown the daemon on idle by default""

---

PackageKit.doap
client/pkcon.xml
client/pkmon.xml
docs/html/pk-faq.html
docs/html/pk-reference.html
etc/Vendor.conf
lib/packagekit-glib2/pk-client.c
policy/org.freedesktop.packagekit.policy.in

Fixes #618
Split into three commits to make separation of concerns easier.
- metadata: Remove reference to defunct screenshots URL
- metadata: replace defunct www.packagekit.org URL with freedesktop URL
- docs: replace defunct www.packagekit.org URL with freedesktop URL

Replace www.packagekit.org domain with Freedesktop URL

---

lib/packagekit-glib2/pk-progress.c

Avoid leaking the sender value.
Closes #623

progress: Free the sender value on finalize

---

lib/packagekit-glib2/pk-enum.c

Fixes: aa07e0b77bd297cf9fd617ae9b8dd7e0cf218c50 ("Use the term DDE instead of deepin")

packagekit-glib2: Use the correct enum for DDE

---

.cirrus.yml

That makes it easier to identify when looking at the pipelines at a glance.

ci: Update the name of the FreeBSD CI pipeline

---

src/pk-engine.c

On FreeBSD the config file is located under /usr/local prefix.

Make use of SYSCONFDIR definition when setting a config file watch.

---

backends/dnf/pk-backend-dnf.c
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-client.h
src/pk-backend-job.c
src/pk-backend-job.h
src/pk-transaction.c

Allow returning package details with download size including the dependencies, which provides more accurate information, especially for packages, which are split to a binary package and to a data package, like the games.
Use this option in the DNF backend.

Add an option to count download size with dependencies

---

lib/packagekit-glib2/pk-category.c
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-control.c
lib/packagekit-glib2/pk-details.c
lib/packagekit-glib2/pk-distro-upgrade.c
lib/packagekit-glib2/pk-error.c
lib/packagekit-glib2/pk-eula-required.c
lib/packagekit-glib2/pk-files.c
lib/packagekit-glib2/pk-item-progress.c
lib/packagekit-glib2/pk-media-change-required.c
lib/packagekit-glib2/pk-package.c
lib/packagekit-glib2/pk-progress.c
lib/packagekit-glib2/pk-repo-detail.c
lib/packagekit-glib2/pk-repo-signature-required.c
lib/packagekit-glib2/pk-require-restart.c
lib/packagekit-glib2/pk-results.c
lib/packagekit-glib2/pk-source.c
lib/packagekit-glib2/pk-task.c
lib/packagekit-glib2/pk-transaction-past.c
lib/packagekit-glib2/pk-update-detail.c
src/pk-spawn.c

We are never doing dynamic construction of name, nickname or blurb. The GObject manual claims that it allows internal performance improvements.

Add G_PARAM_STATIC_STRINGS to all properties

---

src/meson.build

We used to get that implicitly through GModule .pc file defining -Wl,--export-dynamic so that modules could reference symbols in the main executable.
With newer GLib including glib@11bdd6fc the gmodule .pc file will no longer define this compiler flag in a way that works for us, resulting in errors like:
packagekitd[2394]: Failed to load the backend: opening module zypp failed : /usr/lib64/packagekit-backend/libpk_backend_zypp.so: undefined symbol: pk_backend_job_require_restart

packagekitd: Use export_dynamic explicitly

---

data/meson.build

From https://bugs.debian.org/1006631:
> dbus supports policy files in both `/usr/share/dbus-1/system.d` and
> `/etc/dbus-1/systemd`. [The] recently released dbus 1.14.0, officially
> deprecates installing packages' default policies into `/etc/dbus-1/systemd`,
> instead reserving it for the sysadmin. This is the same idea as the
> difference between `/usr/lib/udev/rules.d` and `/etc/udev/rules.d`.

data/meson.build: Install dbus policy in /usr/share, not /etc

---

backends/apt/apt-job.cpp

We should either set the `'REG_EXTENDED'` flag (Extended Regular Expressions) to `regcomp()` and use the `"|"` regex pattern, or use the `"\\|"` regex pattern, as per the BRE (Basic Regular Expressions), which is the default when 'REG_EXTENDED' flag is not set.
From `'man grep'`:
Basic vs Extended Regular Expressions:
In basic regular expressions the meta‐characters ?, +, {, |, (, and ) lose their special meaning; instead use the backslashed versions \?, \+, \{, \|, \(, and \).

apt: Fix 'search-file' regexp as per BRE pattern (which is the default)

---

backends/test/helpers/search-name.sh
tests/data/pk-spawn-test.sh

This unbreaks most of tests on FreeBSD.
Unfortunately, one test is plagued by the same problem as described in https://github.com/ximion/appstream/pull/520 so I didn't enable testing yet.

Use portable shebang in shell scripts.

---

src/pk-transaction.c

Follow up to commit 96a05994d.
Resolves: #656
```
$ /usr/bin/pkcon -p get-details /etc/passwd
Transaction:	Getting details
Status: 	Waiting in queue
The daemon crashed mid-transaction!
```
```
Sep 25 20:20:19 linux packagekitd[425371]: PackageKit:ERROR:../src/pk-transaction.c:5530:pk_transaction_dispose: assertion failed: (transaction->priv->emitted_finished)
Sep 25 20:20:19 linux packagekitd[425371]: Bail out! PackageKit:ERROR:../src/pk-transaction.c:5530:pk_transaction_dispose: assertion failed: (transaction->priv->emitted_finished)
```

transaction: We only need to emit finished when we were committed

---

client/pk-console.c
lib/packagekit-glib2/pk-client.c
src/pk-backend-job.c

trivial: Specify metadata 'cache-age' usage more clearly

---

docs/html/pk-help.html

The IRC channel on Freenode was abandoned long ago, and the one on Libera Chat is dead. As both major stakeholders (GNOME and KDE) use Matrix primarily now, let's move there so that they can talk to us.

docs: Update real-time chat room to point to the new Matrix room

---

src/pk-engine.c
src/pk-transaction.c

pk_strlen() cannot return larger values than the sentinel value (1024) in this case. This invalid check could allow an unprivileged user to consume all of the system's memory (tested for versions <= 1.2.6).

Check string length correctly to prevent memory over-consumption (RHEL-19527)

---

client/pk-monitor.c
docs/html/pk-matrix.html
lib/packagekit-glib2/pk-control.c
lib/packagekit-glib2/pk-control.h
src/org.freedesktop.PackageKit.xml
src/pk-backend.c
src/pk-engine.c

Similar to the "updates-changed" signal emit "installed-changed" when
the backend notifies about changes in the installed apps, thus the library
user can update its UI accordingly. The signal only means it's possible
something changed, it doesn't mean there changed anything.
In case of the libdnf backend this may require https://github.com/rpm-software-management/libdnf/pull/1542 on some systems.

lib: Notify when installed database changed

---

lib/packagekit-glib2/pk-category.c
lib/packagekit-glib2/pk-client.c
lib/packagekit-glib2/pk-progress.c

Use G_DEFINE_TYPE_WITH_PRIVATE which does everything for us. Also use GParamSpec directly to notify a property and use *_get_instance_private() to access the PkClientPrivate structure directly.

PkClient/Progress/Category: Use a more modern GObject style

---

client/pk-offline-update.c
lib/packagekit-glib2/pk-progress-bar.c

Some languages like Turkish and French (and more) uses another percentage format other than 100% (%100 and 100 % respectively). Lack of i18n on UI strings causes an incohesive look, and wrong grammar-wise.
Fixes #633.

Apply i18n for percentage values

---

client/pk-offline-update.c

`case PK_PROGRESS_TYPE_PERCENTAGE` is just a label and doesn't offer any scope as such. So, `tmp_perc` auto variable will be allocated in the stack, but will not be initialized to `NULL` for `case:` statements other than `PK_PROGRESS_TYPE_PERCENTAGE`, causing GLib to consider the `tmp_perc` garbage value as a valid memory address allocated via `g_malloc()`, triggering an invalid `free()` causing the crash.
Rather than adding a scope `{}` within `case`, and causing a huge noise in git diff, we just move the declaration to an upper scope.

pk-offline-update: Fix crash due to invalid g_auto declaration in switch / case

---

client/pk-offline-update.c
po/POTFILES.in

Apparently the grammatical correct dash here is em, not a hyphen or en dash.

pk-offline-update: Add file to POTFILES

---

lib/packagekit-glib2/pk-package.c

Fixes the following assertion failures in Debian Stable (12 / bookworm), when there are security updates (e.g firefox)
`(pkcon:23385): PackageKit-CRITICAL **: 14:13:18.629: pk_package_set_update_severity: assertion 'update_severity == PK_INFO_ENUM_UNKNOWN || update_severity == PK_INFO_ENUM_LOW || update_severity == PK_INFO_ENUM_NORMAL || update_severity == PK_INFO_ENUM_IMPORTANT || update_severity == PK_INFO_ENUM_CRITICAL' failed`

PkPackage: Handle all cases for 'update-severity' property

---

backends/apt/pkg-list.cpp

Fixes: https://github.com/PackageKit/PackageKit/issues/733

apt: Prefer deb version comparison to strcmp

---

lib/packagekit-glib2/pk-progress.c

And remove an invalid free of the item progress object at the same time. This was never a problem in practice, because it had already been cleared (correctly, using `g_object_unref()`) in `dispose`.

pk-progress: Fix a leak of package ID

---

client/pk-offline-update.c

`g_prefix_error()` does nothing if the `error` or `*error` is NULL. So, we crash when accessing `error->message`.
Also, the error message is not propagated to the caller due to this issue.

pk-offline-update: Fix crash during error cases

---

lib/packagekit-glib2/pk-control.c

Fixes the following crash:
```
$ pkcon get-time get-updates
(pkcon:28486): PackageKit-CRITICAL **: 20:31:50.933: pk_control_get_time_since_action_finish: assertion 'g_async_result_is_tagged (res, pk_control_get_transaction_list_async)' failed Segmentation fault
```
With fix:
```
$ pkcon get-time get-updates
Time since: 165s
```

PkControl: Fix crash with 'get-time' transaction

---

backends/dnf/pk-backend-dnf.c
backends/zypp/pk-backend-zypp.cpp

This was already documented in the [‘package component provides naming’ spec](./docs/provides-component-naming.txt), so should be uncontroversial.
This is part of a plan to drop the fedora-langpacks plugin from gnome-software, and replace it with the equivalent of a call to `pkcon what-provides 'language(zh_CN)'` (for example).
See https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/2055#note_2134286

dnf/zypp: Add support for language(ll_CC) to what-provides queries

---

backends/alpm/meson.build
backends/alpm/pk-alpm-config.c
backends/alpm/pk-alpm-transaction.c

In libalpm alpm_conflict_t package struct members are now of type alpm_pkg_t instead of char*.
libalpm sadly does not expose the version in `libalpm.h` in theory this can be made backwards compatible, but not sure how to hack that in with `pkgconf --modversion libalpm` and most distro's shipping pacman are rolling release so should have pacman 6.1

alpm: add compatibility with libalpm 14

---

backends/dnf/meson.build
backends/dnf/notify_packagekit.conf
backends/dnf/notify_packagekit.cpp
tests/ci/Dockerfile-fedora

Just like #600, we should do the same for dnf5

Add dnf5 posttrans notify plugin

---

lib/packagekit-glib2/pk-client.c

The daemon returns "op not supported by the backend" as part of the method call response, but this response can be received after the "Destroy" signal, which causes infinite wait for the transaction end and runtime warnings about NULL error being passed to the g_task_return_error() on the client side.
This is a regression from commit https://github.com/PackageKit/PackageKit/commit/44215db95d9cfda23045d9a9b97175519f473eb2

pk-client: Fix runtime warning when backend does not support role

---

src/pk-engine.c

The original code does not produce a warning on a system without the org.freedesktop.login1 service. The proxy object gets created neverthless and this glib issue [1] hints that it is the owner name that should be checked for NULL.
The correct fix belongs to glib but for now workaround it on the PackageKit side.
[1] https://gitlab.gnome.org/GNOME/glib/-/issues/879

Fix check in pk_engine_proxy_logind_cb

---

backends/alpm/pk-alpm-update.c

Refer https://github.com/PackageKit/PackageKit/issues/661

alpm: Use 'alpm_errno()' rather than incorrect 'errno' for libalpm errors

---

backends/entropy/meson.build
backends/portage/meson.build

Fixes https://github.com/PackageKit/PackageKit/issues/694

entropy/portage: Fix missing 'comma' in meson.install_data ()

---

lib/packagekit-glib2/pk-task.c

Make sure to not drop a reference to an object that is owned by the GSource.

pk-task: pk_task_user_accepted/declined_idle_cb actually take an unowned gtask

---

lib/packagekit-glib2/pk-client.c

Set both XDG_RUNTIME_DIR and WAYLAND_DISPLAY in the helper's environment.
Addittionally set XAUTHORITY which is necessary for connecting to XWayland, in case Wayland wasn't available.

pk-client: Allow debconf helper to display Wayland windows

---

backends/apt/gst-matcher.cpp
backends/apt/meson.build
backends/apt/tests/apt-tests.cpp
backends/apt/tests/definitions.cpp
backends/apt/tests/meson.build

When the list of GstCaps specified is empty, and the only modifier we're given is ()(64bit), our regex eats the outer parenthesis so we're left with ")(64bit" while trying to match "()(64bit".
This change would introduce a trailing comma when the list of specified GstCaps is instead not empty, which gst_caps_from_string today can handle, but for abundance of caution let's avoid it.
Test cases:
```
pkcon what-provides "gstreamer1(decoder-audio/mpeg)(mpegversion=4)()(64bit)"
pkcon what-provides "gstreamer1(decoder-audio/mpeg)(mpegversion=4)"
pkcon what-provides "gstreamer1(decoder-video/x-h265)()(64bit)"
pkcon what-provides "gstreamer1(decoder-video/x-h265)"
```

apt: Fix matching gstreamer pkgs where the only modifier is ()(64bit)

---

backends/apt/20packagekit

which doesn't really do anything useful for ostree-managed systems (such as rpm-ostree)

apt: not call dbus on ostree-managed systems

---

lib/packagekit-glib2/pk-control.c

Use G_DEFINE_TYPE_WITH_PRIVATE, notify with pspec when possible, use the latest syntax (from more than a decade ago) on the return documentation.

PkControl: Modernize the codebase

---

backends/apt/meson.build

We are not exactly creating a library here.

apt: Use shared_module instead of shared_library as this is a loaded module

---

backends/apt/apt-job.cpp
backends/apt/pk-backend-apt.cpp

These functions return std::string_view now; adjust the callers to wrap them in std::string{}. An alternative would be to use append() instead of a temporary string object but this is not performance critical anyway.
I'm cherry-picking this in the package, I already committed the patch in salsa, and will upload once APT transition starts and it has been built everywhere.

apt: Adjust for libapt-pkg7.0 API

---

backends/zypp/pk-backend-zypp.cpp

This fixes a bug where, with zypper backend, PackageKit crashes on empty search strings.
After you make a call with empty search string , you'll get a journal message that looks something like this:
```
Feb 25 11:06:41 tw packagekitd[1513]: terminate called after throwing an instance of 'std::logic_error'
Feb 25 11:06:41 tw packagekitd[1513]:   what():  basic_string: construction from null is not valid
Feb 25 11:06:41 tw systemd-coredump[1540]: Process 1513 (Zypp-main) of user 0 terminated abnormally with signal 6/ABRT, processing...
Feb 25 11:06:41 tw systemd[1]: Started Process Core Dump (PID 1540/UID 0).
Feb 25 11:06:41 tw systemd-coredump[1541]: [🡕] Process 1513 (Zypp-main) of user 0 dumped core.
Stack trace of thread 1519:
#0  0x00007f976069a13c __pthread_kill_implementation …
```

zypp: Raise exception on empty search string

---

backends/apt/apt-job.cpp

This is needed for download size reporting to work in PK clients which use the `download-size` property (introduced in 3741c6842b) in `get-details` response. `download-size` property is available only when the PK backend uses `pk_backend_job_details_full()`, not otherwise.
Fixes: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1026076
I'll submit changes for other backends in separate pull requests.

apt: Use 'pk_backend_job_details_full()' so download size is reported properly

---

backends/dnf/dnf-backend-vendor-openmandriva.c

- rename "unsupported" repository to "extra"
- add riscv64 architecture

OpenMandriva: small repo changes

---

backends/alpm/pk-backend-alpm.c

Fixes the following warning: (from https://github.com/PackageKit/PackageKit/actions/runs/14432889256/job/40469819487?pr=787)
```
../backends/alpm/pk-backend-alpm.c: In function 'pk_alpm_logcb': ../backends/alpm/pk-backend-alpm.c:60:9: warning: function 'pk_alpm_logcb' might be a candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
60 |         output = g_strdup_vprintf (format, args);
|
```
`pk_alpm_logcb` function signature is from `libalpm/alpm.h` (public API), so nothing much we can do except ignore the warning.
`typedef void (*alpm_cb_log)(alpm_loglevel_t, const char *, va_list);`

alpm: Fix 'pk_alpm_logcb' printf format warning

---

.cirrus.yml

Removes the `-v` ninja build flag, as there is just too much build output. 
https://github.com/PackageKit/PackageKit/pull/842 fixes all build issues related to `FreeBSD` (which uses `Clang`).
@arrowd: Thoughts?

ci: Reduce verbose logs in freebsd build

---

backends/zypp/meson.build

This is just an interim fix until the deprecation warnings are fixed.
Refer: https://github.com/PackageKit/PackageKit/issues/839

ci: Disable deprecation errors in zypp backend temporarily

---

backends/apt/apt-job.cpp
backends/apt/apt-sourceslist.cpp
backends/apt/apt-sourceslist.h
backends/apt/deb822.cpp
backends/apt/deb822.h
backends/apt/meson.build
backends/apt/pk-backend-apt.cpp
backends/apt/tests/apt-tests.cpp
backends/apt/tests/meson.build
backends/apt/tests/testdata/sources/debian.sources
backends/apt/tests/testdata/sources/ignorethis.list.save
backends/apt/tests/testdata/sources/mozilla.list

Honestly, the entire APT sources handling needs a full rewrite, and I was *so* close to doing it. Adding deb822 sources to the existing data model is like cramming a square piece into a smaller round hole.
This will work though, and hopefully when at some point we can drop support for legacy sources, all of this can be rewritten properly.
For now, keeping the old code working, and the old data model somewhat intact (which answers the not-so-simple "what even is a repository?" question for us...) was likely the right way to go.
When rewriting sources files, the code tries to be as non-destructive as possible, keeping comments etc. intact.

apt: Implement support for Deb822 sources.list

---

backends/apt/meson.build
backends/apt/tests/meson.build

Include it in the module and in the test executable. No behavioral changes.

apt: Define an apt backend static library

---

lib/packagekit-glib2/pk-control.c

The error is already propgated programmatically as a `GError`, which allows the caller to handle it as they see fit.
Additionally printing a warning message slightly undermines the caller’s ability to ignore errors here, as it will cause an abort if running with `G_DEBUG=fatal-warnings` (for example).
This is causing problems when running PackageKit in gnome-software’s CI, which doesn’t support proxy settings (as no logind session is running) — the tests are run with `G_DEBUG=fatal-warnings`, and this warning then becomes fatal.

pk-control: Use g_debug() rather than g_warning() for proxy error

---

backends/dnf/dnf-backend-vendor-rosa.c

restricted repository was removed some years ago in all dnf-based plaforms. i586 was renamed to i686 in all dnf-based platforms. Added new arches.
See: https://mirror.rosa.ru/rosa/rosa13 and https://abf-downloads.rosa.ru/rosa13

dnf: update ROSA config

---

backends/apt/pk-debconf-helper.c
lib/packagekit-glib2/pk-client-helper.c

Fixes the following assertion errors when `pk-debconf-helper` exits.
```
Aug 19 19:45:19 debian pk-debconf-help[22042]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 19 19:45:19 debian pk-debconf-help[22042]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
Please refer commit log for more details.

apt: debconf-helper: Fix assertion errors

---

backends/apt/apt-utils.cpp
backends/apt/apt-utils.h
backends/apt/tests/apt-tests.cpp

Fixes the parsing of the changelog dates, which resulted on the `issued` and `updated` date parameters never getting filled.
According to `deb-changelog` specification, the dates in the apt changelog entries do not follow RFC1123 format (which doesn't handle timezones), buut is compatible with RFC2822/RFC5322, that is:
"day-of-week, dd month yyyy hh:mm:ss +zzzz"
Also, rework the conditions to check first for the changelog date line (starts with " --") so it doesn't get shadowed by the general condition (starts with " ")
Some examples of the reported dates on the client side, by adding some debug output to discover:
```
"kde-cli-tools;4:6.3.4-0ubuntu1;amd64;ubuntu-plucky-universe"
Issued: QDateTime(2025-03-29 15:13:49.000 UTC-05:00 Qt::OffsetFromUTC -18000 s )
Updated: QDateTime(2025-04-02 …
```

apt: Fix updated and issued dates on changelog parsing

---

backends/apt/apt-job.cpp
backends/apt/gst-matcher.cpp
backends/apt/gst-matcher.h
backends/apt/tests/apt-tests.cpp

The ()(64bit) suffix is an RPM artifact, where it is used to distinguish between the primary and secondary architecture in a 2-arch system. It doesn't translate precisely to DPKG, where multi-arch is not limited to one secondary architecture. Let's use it the same way RPM would and only match the native arch.

apt: Handle gstreamer ()(64bit) suffix on any architecture

---

backends/alpm/pk-alpm-packages.c

Tested on latest archlinux.
- `gnome-software` package is installed.
- `gnome-builder` package is not installed.
```
[sid@archlinux pkg]$ pacman -Qi gnome-software | grep ^Installed
Installed Size  : 15.89 MiB
[sid@archlinux pkg]$ ls -l /var/cache/pacman/pkg/gnome-builder-48.3-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 11107151 Aug 16 05:33 /var/cache/pacman/pkg/gnome-builder-48.3-1-x86_64.pkg.tar.zst
[sid@archlinux pkg]$ pacman -Qi -p /var/cache/pacman/pkg/gnome-builder-48.3-1-x86_64.pkg.tar.zst | grep ^Installed
Installed Size  : 27.08 MiB
```
```
[sid@archlinux pkg]$ pkcon get-details gnome-software
Resolving                               [=========================]         
Getting details                         [=========================]         
Finished …
```

alpm: Use 'pk_backend_job_details_full()' to report download size

---

lib/packagekit-glib2/pk-offline.c

From what I gather, we can't use `g_autofree` on this pointer, because it must be freed with `g_strfreev`. The `g_autoptr(Gstrv)` implementation doesn't exist either.
This is a follow-up to https://github.com/PackageKit/PackageKit/pull/852#pullrequestreview-3270248754

pk-offline.c: Plug a memleak I introduced earlier
